import { z } from 'astro/zod';
import data from '../data/footpaths.json';

/** Generated by scripts/import-photos.mjs; decoded here so pages get real types. */
const footpath = z.object({
  id: z.string(),
  location: z.string(),
  lat: z.number(),
  lng: z.number(),
  date: z.string(),
  photos: z.array(z.object({ file: z.string(), caption: z.string() })),
});

export type Footpath = z.infer<typeof footpath>;

export function loadFootpaths(): Footpath[] {
  return footpath.array().parse(data);
}
